# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4e1b90376ce0fe6c85c7b3c554c14948970d6c9b2d6d74d81a8d3ed493f93aeccad026aab0a9dbdc47d2b2d5d602105baba30ca4b0673660f00e85588cd97e8

test:
  secret_key_base: b17a64d27b0ef61d6b328bc69894a9d3d161de52b6b20a3394dc3b38d9c1670391e6dac9aa04eccda239a5385fbc38cd6bed5ed7ffa6f24e5f33c90967039538

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
